repos:
  # Hooks de base
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict

  # ESLint pour le backend
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.30.1
    hooks:
      - id: eslint
        files: \.(js|mjs)$
        types: [file]
        additional_dependencies:
          - eslint@^9.30.1
          - '@eslint/js@^9.30.1'

  # Prettier pour le formatage
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(js|json|md)$
        types: [file]

  # Tests pour le backend
  - repo: local
    hooks:
      - id: backend-tests
        name: Backend Tests
        entry: npm run test:ci
        language: system
        pass_filenames: false
        always_run: true

  # Vérification des dépendances
  - repo: local
    hooks:
      - id: check-dependencies
        name: Check Dependencies
        entry: npm audit --audit-level=moderate
        language: system
        pass_filenames: false
        always_run: true
